name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
    - name: make
      run: make
      
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libavcodec58 libavformat58 libswscale5 libswresample3 libavutil56 libusb-1.0-0 libpcre2-16-0 libdouble-conversion3 libxcb-xinput0 libxcb-xinerama0
 #       sudo sh install_spinnaker.sh
 
    - name: Install spinnmaker
      run: wget https://meta.box.lenovo.com/v/link/view/a1995795ffba47dbbe45771477319cc3
      
#     - name: building
#       run: |
#         mkdir build && cd build
#         cmake ..
